gatekeeper: have a VLAN tag for IPv4 and another for IPv6
AltraMayor/gatekeeper pull request #442
Opened 2020-11-23 00:07 UTC by mengxiang0811

This patch closes #437.

2020-11-24 15:09 UTC, AltraMayor requested changes
**gatekeeper: have a VLAN tag for IPv4 and another for IPv6**

2020-11-24 15:09 UTC, AltraMayor commented on lib/l2.c
> +		}
Variable `proto_name` is meant to improve log entries. Moreover, `verify_l2_hdr()` is only called twice. It's better to add parameter `uint16_t vlan_tag_be` to `verify_l2_hdr()` and get this information from callers.

2020-11-24 15:13 UTC, AltraMayor requested changes
**gatekeeper: have a VLAN tag for IPv4 and another for IPv6**

2020-11-24 15:13 UTC, AltraMayor commented on cps/main.c
>  				rte_be_to_cpu_16(eth_hdr->ether_type));
`eth_hdr->ether_type` is big endian, while `RTE_ETHER_TYPE_IPV4` is host endian.

2020-11-25 12:11 UTC, AltraMayor requested changes
**gatekeeper: have a VLAN tag for IPv4 and another for IPv6**

2020-11-25 12:11 UTC, AltraMayor commented on lua/net.lua
> +	local front_ipv6_vlan_tag = 0x123
Replace line `local front_ipv6_vlan_tag = 0x123` with `local front_ipv6_vlan_tag = front_ipv4_vlan_tag`.

Do the same for the back interface as well.

2020-11-27 23:55 UTC, mengxiang0811 commented
This is ready for another review.

2020-11-30 16:16 UTC, merged