fib: make gateway prefix check more robust
AltraMayor/gatekeeper pull request #443
Opened 2020-11-23 03:11 UTC by cjdoucette

2020-11-24 16:22 UTC, AltraMayor requested changes
**fib: make gateway prefix check more robust**

2020-11-24 16:22 UTC, AltraMayor commented on gk/fib.c
> +			prefix->addr.proto, gw_addr->proto);
Add `prefix->str` to the log entry.

2020-11-24 16:22 UTC, AltraMayor commented on gk/fib.c
> +	}
Add `prefix->str` to the log entry.

2020-12-18 12:34 UTC, cjdoucette commented
Ready for another review.

2020-12-18 14:29 UTC, merged