CPS: wait for the kernel to set up KNI interfaces
AltraMayor/gatekeeper pull request #480
Opened 2021-05-23 23:30 UTC by AltraMayor

There is a race condition between the kernel and Gatekeeper that occasionally terminates the initialization of Gatekeeper with
the following log entries:

```
GATEKEEPER CPS: mnl_cb_run: cannot bring KNI kni_front up: No such device
GATEKEEPER CPS: Failed to configure KNI link on the front iface
```

OR

```
GATEKEEPER CPS: mnl_cb_run: cannot bring KNI kni_back up: No such device
GATEKEEPER CPS: Failed to configure KNI link on the back iface
```

This patch waits for the kernel to assign interface indexes to the KNI interfaces before setting the KNI interfaces to avoid
the race condition.

2021-05-24 03:37 UTC, mengxiang0811 requested changes
**CPS: wait for the kernel to set up KNI interfaces**

2021-05-24 03:37 UTC, mengxiang0811 commented on cps/main.c
> +	 */
Style: need to align with the above statements.

2021-05-24 03:55 UTC, mengxiang0811 commented on cps/main.c
> +	} while (i > wait_trials);
If `wait_trials` is greater than `0`, then this condition will always be `false` after the first call of `if_nametoindex()`.

2021-05-24 11:59 UTC, AltraMayor commented
Pull request ready for another review.

2021-05-25 13:18 UTC, AltraMayor commented
The root cause of this issue has been found: `systemd` was renaming the KNI interfaces. `systemd` may be configured to rename an interface based **only** on its MAC address. This is done in production to have friendly interface names to be used in scripts. However, since a KNI interface in Gatekeeper has the same MAC address as its corresponding physical interface, this creates many problems.

The solution to use the PCI addresses of physical interfaces instead of their MAC addresses to identify them for `systemd`.

2021-05-25 13:18 UTC, closed without merging