Gatekeeper: have all log accounted on a functional block basis
AltraMayor/gatekeeper pull request #537
Opened 2022-01-18 08:21 UTC by mengxiang0811

2022-01-18 13:57 UTC, AltraMayor requested changes
**dyc: have log accounted on a functional block basis**

2022-01-18 13:57 UTC, AltraMayor commented on lua/gatekeeper/staticlib.lua
> +	RTE_LOGTYPE_USER1 = 24U, /* User-defined log type 1. */
Where's this constant needed? If it is needed, why shouldn't we use `BLOCK_LOGTYPE` instead?

2022-01-18 13:57 UTC, AltraMayor commented on lua/examples/example_of_dynamic_config_request.lua
> -staticlib.c.rte_log_set_global_level(staticlib.c.RTE_LOG_ERR)
This example is still valuable and should support it since it helps us to investigate problems in DPDK.

2022-01-18 13:57 UTC, AltraMayor commented on lua/examples/example_of_dynamic_config_request.lua
>  end
Given that `cpsc.log_type` is going away, can't we drop these lines of code as well?

2022-01-18 13:57 UTC, AltraMayor commented on lua/examples/example_of_dynamic_config_request.lua
>  end
Why is this code which refers to the CPS block being changed in a patch for the dynamic configuration block? The same comment applies code below and my previous comment.

2022-01-18 13:57 UTC, AltraMayor commented on lua/gatekeeper/staticlib.lua
> -int rte_log_get_level(uint32_t type);
These functions are still useful for debugging DPDK and should be preserved. Group them with the two functions above, and add the comment below to them clarify their purpose.
`/* These functions are meant to help one to investigate issues that depend on the internals of DPDK. */`
Break this comment into as many lines as needed.

2022-01-18 14:15 UTC, AltraMayor commented on include/gatekeeper_lls.h
> -extern int lls_logtype;
We are dropping the `extern` definition of `lls_logtype`, but not the actual definition of `lls_logtype`.

2022-01-24 01:49 UTC, mengxiang0811 commented
This rebase is ready for another review.

2022-01-25 19:35 UTC, merged