Pktmbuf free
AltraMayor/gatekeeper pull request #631
Opened 2023-02-27 07:06 UTC by mengxiang0811

2023-02-28 12:22 UTC, AltraMayor requested changes
**lib/acl: adopt rte_pktmbuf_free_bulk()**

2023-02-28 12:24 UTC, AltraMayor requested changes
**gt: adopt rte_pktmbuf_free_bulk()**

2023-02-28 12:24 UTC, AltraMayor commented on gt/main.c
> +				num_tx - num_tx_succ);
Style. Given that you had to break the call `rte_pktmbuf_free_bulk()` into two lines, bring back the braces of the `if` statement.

2023-03-06 07:32 UTC, mengxiang0811 commented
This PR is ready for another review.

2023-03-07 13:20 UTC, merged